name: Tony Castro Music
favicon: null
layout_spectrum: 0
typography_spectrum: 0.506383
title: Tony Castro Music
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8499AA'
    - '#B5C3CC'
    - '#748396'
    - '#50637B'
    - '#1C3657'
  brandStrength: 0.793617
  lightness: 0.4212766
  saturation: 0.4957447
  rhythmicContrast: 0.4978724
purpose: []
