name: tony castro music
favicon: null
layout_spectrum: 0.35461
typography_spectrum: 0.9719870558474213
title: Tony Castro Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15212d'
    - '#716f7c'
    - '#f5efd7'
    - '#993947'
    - '#b19e97'
  brandStrength: 0.9026359752751887
  lightness: 0.7524198913015425
  saturation: 0.21665435703471303
  rhythmicContrast: 0.3035087857861072
purpose: []
