name: Tony Castro Music
favicon: null
layout_spectrum: 1
typography_spectrum: 0.506383
title: Tony Castro Music
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F5F5F6'
    - '#01013D'
    - '#A4A2B5'
    - '#34343F'
    - '#3B5BA7'
  brandStrength: 0.6744681
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
