name: tony castro music
favicon: null
layout_spectrum: 0.1321
typography_spectrum: 0.61297
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Tony Castro Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15212d'
    - '#716f7c'
    - '#f5efd7'
    - '#993947'
    - '#b19e97'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.2553191
purpose: []
