title: Tony Castro Music
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4957447
  brandStrength: 1
  lightness: 0.6723405
  brandColors:
    - '#305D96'
    - '#102135'
    - '#1F3B60'
    - '#050A10'
    - '#E3E7EB'
  rhythmicContrast: 0.4978724
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Tony Castro Music
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.506383
layout_spectrum: 0.4851064
